hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix:   /login

google_login:
    path: /login/check-sensio
